version: "3.8"

services:
  frontend:
    dns:
      - 8.8.8.8
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend

  backend:
    dns:
      - 8.8.8.8
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/tsconfig.json:/app/tsconfig.json
      - /app/node_modules
    environment:
      - PORT=5000
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/book-management
      - JWT_SECRET=s3cr3tZ++xD7pLwA5Yj2hPzLz4MzV9nZqRlFq0ZMBUgf+soYeymZ6o5RMFblQkZlEB9GJ
      - JWT_EXPIRES_IN=7d
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
